// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineSurvey.Repos;

#nullable disable

namespace OnlineSurvey.Repos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250123154918_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineSurvey.DataAccessLayer.Entities.Expectations", b =>
                {
                    b.Property<int>("ObjectiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectiveID"));

                    b.Property<int>("ExpectedWeight")
                        .HasColumnType("int");

                    b.Property<string>("FocusArea")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ObjectiveID");

                    b.ToTable("Objective");

                    b.HasData(
                        new
                        {
                            ObjectiveID = 1,
                            ExpectedWeight = 8,
                            FocusArea = "Internal Meetings"
                        },
                        new
                        {
                            ObjectiveID = 2,
                            ExpectedWeight = 8,
                            FocusArea = "Client Meetings"
                        },
                        new
                        {
                            ObjectiveID = 3,
                            ExpectedWeight = 5,
                            FocusArea = "Emails & Phone / Skype calls"
                        },
                        new
                        {
                            ObjectiveID = 4,
                            ExpectedWeight = 5,
                            FocusArea = "Research"
                        },
                        new
                        {
                            ObjectiveID = 5,
                            ExpectedWeight = 2,
                            FocusArea = "DB Design"
                        },
                        new
                        {
                            ObjectiveID = 6,
                            ExpectedWeight = 5,
                            FocusArea = "Architecture Design and Planning"
                        },
                        new
                        {
                            ObjectiveID = 7,
                            ExpectedWeight = 30,
                            FocusArea = "Back-end Development"
                        },
                        new
                        {
                            ObjectiveID = 8,
                            ExpectedWeight = 22,
                            FocusArea = "Front-end Development"
                        },
                        new
                        {
                            ObjectiveID = 9,
                            ExpectedWeight = 5,
                            FocusArea = "Integration"
                        },
                        new
                        {
                            ObjectiveID = 10,
                            ExpectedWeight = 10,
                            FocusArea = "Testing"
                        });
                });

            modelBuilder.Entity("OnlineSurvey.DataAccessLayer.Entities.Questions", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<string>("QuestionDescription")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("QuestionID");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            QuestionDescription = "Internal Meetings"
                        },
                        new
                        {
                            QuestionID = 2,
                            QuestionDescription = "Client Meetings"
                        },
                        new
                        {
                            QuestionID = 3,
                            QuestionDescription = "Emails & Phone / Skype calls"
                        },
                        new
                        {
                            QuestionID = 4,
                            QuestionDescription = "Research"
                        },
                        new
                        {
                            QuestionID = 5,
                            QuestionDescription = "DB Design"
                        },
                        new
                        {
                            QuestionID = 6,
                            QuestionDescription = "Architecture Design and Planning"
                        },
                        new
                        {
                            QuestionID = 7,
                            QuestionDescription = "Back-end Development"
                        },
                        new
                        {
                            QuestionID = 8,
                            QuestionDescription = "Front-end Development"
                        },
                        new
                        {
                            QuestionID = 9,
                            QuestionDescription = "Integration"
                        },
                        new
                        {
                            QuestionID = 10,
                            QuestionDescription = "Testing"
                        });
                });

            modelBuilder.Entity("OnlineSurvey.DataAccessLayer.Entities.RespondentResult", b =>
                {
                    b.Property<int>("ResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseID"));

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpectationGap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ManagersWeight")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("RespondentsWeight")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ResponseID");

                    b.ToTable("RespondentResult");
                });

            modelBuilder.Entity("OnlineSurvey.DataAccessLayer.Entities.Respondents", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("UserID");

                    b.ToTable("Respondent");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Password = "Smith",
                            RoleID = 1,
                            UserName = "Marcell"
                        },
                        new
                        {
                            UserID = 2,
                            Password = "Snow",
                            RoleID = 2,
                            UserName = "John"
                        },
                        new
                        {
                            UserID = 3,
                            Password = "Eleven",
                            RoleID = 2,
                            UserName = "Kevin"
                        },
                        new
                        {
                            UserID = 4,
                            Password = "DuoLingo",
                            RoleID = 2,
                            UserName = "Joe"
                        },
                        new
                        {
                            UserID = 5,
                            Password = "Watermellons",
                            RoleID = 2,
                            UserName = "Carl"
                        });
                });

            modelBuilder.Entity("OnlineSurvey.DataAccessLayer.Entities.UserRoles", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RoleID");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Worker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
